# Generated by Django 4.1.4 on 2022-12-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Марка')),
                ('mod', models.CharField(max_length=50, verbose_name='Модель')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('specs', models.TextField(verbose_name='Спецификация')),
                ('prise', models.CharField(max_length=50, verbose_name='Цена')),
                ('is_home', models.CharField(max_length=250, verbose_name='Наличие')),
            ],
            options={
                'verbose_name': 'Спецтехника',
                'verbose_name_plural': 'Спецтехника',
            },
        ),
    ]
