# Generated by Django 4.1.4 on 2022-12-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stech_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stech',
            name='photo',
            field=models.ImageField(upload_to='media', verbose_name='Фото'),
        ),
    ]
