# Generated by Django 4.1.4 on 2022-12-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_stech_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otzyv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
                ('text', models.TextField(max_length=1000, verbose_name='Отзыв')),
                ('tel', models.CharField(max_length=12, verbose_name='Телефон')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
