# Generated by Django 4.1.4 on 2023-02-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otzyv',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
